Repository slackapi/deno-slack-sdk, pull requests merged in 2022-09, with the labels that each got.

#105 Add specific instructions on how to implement a function in docs
  docs/functions.md
Labels: documentation

#107 [HERMES-3843] Shim deno fetch api for npm build
  .github/workflows/npm.yml
  build_npm.ts
Labels: bug

#110 Update type parameters to be compatible with Deno 1.26 breaking changes
  src/functions/interactivity/action_router_test.ts
  src/functions/interactivity/types.ts
  src/functions/interactivity/view_router_test.ts
  src/functions/tester/types.ts
  src/functions/types.ts
Labels: enhancement

#108 Adds min supported engines properties to npm build package.json
  build_npm.ts
Labels: enhancement
