Repository slackapi/deno-slack-sdk, pull requests merged in 2022-07, with the labels that each got.

#57 First pass at Action Handlers / a router for actions
  src/dev_deps.ts
  src/functions/routers/action_router.ts
  src/functions/routers/action_router_test.ts
  src/functions/routers/mod.ts
  src/functions/routers/types.ts
  src/functions/tester/mod.ts
  src/functions/tester/types.ts
  src/functions/types.ts
  src/mod.ts
  src/types.ts
Labels: enhancement

#47 Add Non-Slack hosted app manifest types
  src/datastore/mod.ts
  src/datastore/types.ts
  src/dev_deps.ts
  src/functions/mod.ts
  src/functions/types.ts
  src/manifest/manifest_schema.ts
  src/manifest/manifest_test.ts
  src/manifest/mod.ts
  src/manifest/types.ts
  src/manifest/types_util.ts
  src/mod.ts
  src/providers/oauth2/mod.ts
  src/types.ts
  src/types/mod.ts
  src/types/types.ts
  src/workflows/mod.ts
  src/workflows/types.ts
  src/workflows/workflow-step.ts
Labels: enhancement

#66 deno-slack-sdk publish to npm on tag push (new)
  .github/workflows/npm-publish.yml
  .gitignore
  build_npm.ts
Labels: enhancement

#67 Resolves type errors
  src/functions/routers/action_router.ts
Labels: bug

#65 First pass at basic action handler tutorial.
  docs/functions-action-handlers.md
  docs/functions.md
Labels: documentation

#71 Adds RoS App Settings defaults: org_deploy_enabled
  src/manifest/manifest_test.ts
  src/manifest/mod.ts
  src/manifest/types.ts
Labels: enhancement
