Repository slackapi/deno-slack-sdk, pull requests merged in 2023-02, with the labels that each got.

#131 Add manual testing instructs to maintainers guide
  .github/maintainers_guide.md
Labels: documentation

#130 Add format property to StringParameterDefinition type
  src/parameters/types.ts
Labels: enhancement

#135 Export `DefineProperty` on the main `src/mod.ts` file.
  src/mod.ts
Labels: semver:patch

#141 Deno editor configuration
  .github/maintainers_guide.md
  .vscode/settings.json
  deno.jsonc
Labels: documentation, semver:patch

#140 Built in function gen improve
  deno.jsonc
  src/dev_deps.ts
  src/schema/slack/functions/_scripts/README.md
  src/schema/slack/functions/_scripts/generate
  src/schema/slack/functions/_scripts/src/template.ts
  src/schema/slack/functions/_scripts/src/templates/template_function.ts
  src/schema/slack/functions/_scripts/src/templates/template_mod.ts
  src/schema/slack/functions/_scripts/src/templates/template_utils.ts
  src/schema/slack/functions/_scripts/src/templates/test/template_utils_test.ts
  src/schema/slack/functions/_scripts/src/templates/test_template.ts
  src/schema/slack/functions/_scripts/src/templates/types.ts
  src/schema/slack/functions/_scripts/src/test/data/function.json
  src/schema/slack/functions/_scripts/src/test/utils_test.ts
  src/schema/slack/functions/_scripts/src/types.ts
  src/schema/slack/functions/_scripts/src/utils.ts
  src/schema/slack/functions/_scripts/src/write_function_files.ts
  src/schema/slack/functions/add_pin.ts
  src/schema/slack/functions/add_pin_test.ts
  src/schema/slack/functions/add_user_to_usergroup.ts
  src/schema/slack/functions/add_user_to_usergroup_test.ts
  src/schema/slack/functions/archive_channel.ts
  src/schema/slack/functions/archive_channel_test.ts
  src/schema/slack/functions/create_channel.ts
  src/schema/slack/functions/create_channel_test.ts
  src/schema/slack/functions/create_usergroup.ts
  src/schema/slack/functions/create_usergroup_test.ts
  src/schema/slack/functions/delay.ts
  src/schema/slack/functions/delay_test.ts
  src/schema/slack/functions/invite_user_to_channel.ts
  src/schema/slack/functions/invite_user_to_channel_test.ts
  src/schema/slack/functions/mod.ts
  src/schema/slack/functions/open_form.ts
  src/schema/slack/functions/open_form_test.ts
  src/schema/slack/functions/remove_user_from_usergroup.ts
  src/schema/slack/functions/remove_user_from_usergroup_test.ts
  src/schema/slack/functions/reply_in_thread.ts
  src/schema/slack/functions/reply_in_thread_test.ts
  src/schema/slack/functions/send_dm.ts
  src/schema/slack/functions/send_dm_test.ts
  src/schema/slack/functions/send_ephemeral_message.ts
  src/schema/slack/functions/send_ephemeral_message_test.ts
  src/schema/slack/functions/send_message.ts
  src/schema/slack/functions/send_message_test.ts
  src/schema/slack/functions/update_channel_topic.ts
  src/schema/slack/functions/update_channel_topic_test.ts
Labels: enhancement, semver:minor
