Repository slackapi/deno-slack-sdk, pull requests merged in 2023-11, with the labels that each got.

#237 Update slack functions with new type
  src/dev_deps.ts
  src/schema/slack/functions/_scripts/src/templates/test_template.ts
  src/schema/slack/functions/add_pin.ts
  src/schema/slack/functions/add_pin_test.ts
  src/schema/slack/functions/add_user_to_usergroup.ts
  src/schema/slack/functions/add_user_to_usergroup_test.ts
  src/schema/slack/functions/archive_channel.ts
  src/schema/slack/functions/archive_channel_test.ts
  src/schema/slack/functions/create_channel.ts
  src/schema/slack/functions/create_channel_test.ts
  src/schema/slack/functions/create_usergroup.ts
  src/schema/slack/functions/create_usergroup_test.ts
  src/schema/slack/functions/delay.ts
  src/schema/slack/functions/delay_test.ts
  src/schema/slack/functions/invite_user_to_channel.ts
  src/schema/slack/functions/invite_user_to_channel_test.ts
  src/schema/slack/functions/mod.ts
  src/schema/slack/functions/open_form.ts
  src/schema/slack/functions/open_form_test.ts
  src/schema/slack/functions/remove_user_from_usergroup.ts
  src/schema/slack/functions/remove_user_from_usergroup_test.ts
  src/schema/slack/functions/reply_in_thread.ts
  src/schema/slack/functions/reply_in_thread_test.ts
  src/schema/slack/functions/send_dm.ts
  src/schema/slack/functions/send_dm_test.ts
  src/schema/slack/functions/send_ephemeral_message.ts
  src/schema/slack/functions/send_ephemeral_message_test.ts
  src/schema/slack/functions/send_message.ts
  src/schema/slack/functions/send_message_test.ts
  src/schema/slack/functions/update_channel_topic.ts
  src/schema/slack/functions/update_channel_topic_test.ts
  src/schema/slack/types/mod.ts
Labels: semver:minor

#241 Type file id with builtins
  src/dev_deps.ts
  src/schema/slack/functions/_scripts/src/templates/test_template.ts
  src/schema/slack/functions/add_pin.ts
  src/schema/slack/functions/add_pin_test.ts
  src/schema/slack/functions/add_user_to_usergroup.ts
  src/schema/slack/functions/add_user_to_usergroup_test.ts
  src/schema/slack/functions/archive_channel.ts
  src/schema/slack/functions/archive_channel_test.ts
  src/schema/slack/functions/create_channel.ts
  src/schema/slack/functions/create_channel_test.ts
  src/schema/slack/functions/create_usergroup.ts
  src/schema/slack/functions/create_usergroup_test.ts
  src/schema/slack/functions/delay.ts
  src/schema/slack/functions/delay_test.ts
  src/schema/slack/functions/invite_user_to_channel.ts
  src/schema/slack/functions/invite_user_to_channel_test.ts
  src/schema/slack/functions/mod.ts
  src/schema/slack/functions/open_form.ts
  src/schema/slack/functions/open_form_test.ts
  src/schema/slack/functions/remove_user_from_usergroup.ts
  src/schema/slack/functions/remove_user_from_usergroup_test.ts
  src/schema/slack/functions/reply_in_thread.ts
  src/schema/slack/functions/reply_in_thread_test.ts
  src/schema/slack/functions/send_dm.ts
  src/schema/slack/functions/send_dm_test.ts
  src/schema/slack/functions/send_ephemeral_message.ts
  src/schema/slack/functions/send_ephemeral_message_test.ts
  src/schema/slack/functions/send_message.ts
  src/schema/slack/functions/send_message_test.ts
  src/schema/slack/functions/update_channel_topic.ts
  src/schema/slack/functions/update_channel_topic_test.ts
  src/schema/slack/types/mod.ts
Labels: do not merge, semver:minor

#247 Capitalize testing heading in PR template
  .github/PULL_REQUEST_TEMPLATE.md
Labels: documentation, cla:signed
