Repository slackapi/deno-slack-sdk, pull requests merged in 2024-06, with the labels that each got.

#327 New `team_id` type, updates to built-ins, updated builtin function generation script instructions
  deno.jsonc
  src/schema/slack/functions/_scripts/README.md
  src/schema/slack/functions/_scripts/src/templates/template_function.ts
  src/schema/slack/functions/_scripts/src/templates/test_template.ts
  src/schema/slack/functions/_scripts/src/types.ts
  src/schema/slack/functions/add_bookmark.ts
  src/schema/slack/functions/add_bookmark_test.ts
  src/schema/slack/functions/canvas_copy.ts
  src/schema/slack/functions/canvas_copy_test.ts
  src/schema/slack/functions/canvas_create.ts
  src/schema/slack/functions/canvas_create_test.ts
  src/schema/slack/functions/canvas_update_content.ts
  src/schema/slack/functions/canvas_update_content_test.ts
  src/schema/slack/functions/channel_canvas_create.ts
  src/schema/slack/functions/channel_canvas_create_test.ts
  src/schema/slack/functions/create_channel.ts
  src/schema/slack/functions/create_channel_test.ts
  src/schema/slack/functions/create_usergroup.ts
  src/schema/slack/functions/create_usergroup_test.ts
  src/schema/slack/functions/delay.ts
  src/schema/slack/functions/delay_test.ts
  src/schema/slack/functions/invite_user_to_channel.ts
  src/schema/slack/functions/invite_user_to_channel_test.ts
  src/schema/slack/functions/mod.ts
  src/schema/slack/functions/send_dm.ts
  src/schema/slack/functions/send_dm_test.ts
  src/schema/slack/functions/send_ephemeral_message.ts
  src/schema/slack/functions/send_ephemeral_message_test.ts
  src/schema/slack/functions/send_message.ts
  src/schema/slack/functions/send_message_test.ts
  src/schema/slack/functions/share_canvas.ts
  src/schema/slack/functions/share_canvas_test.ts
  src/schema/slack/types/mod.ts
Labels: semver:minor

#330 fix: bump the api dependency
  src/deps.ts
Labels: semver:patch, dependencies

#333 Fix typo in README.md
  src/README.md
Labels: documentation, semver:patch, cla:signed
